name: Lambda Typescript
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: lambda-ts-dist
          path: ./dist
  deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4.3.0
        with:
          name: lambda-ts-dist
          path: ./dist
      - run: echo "Deploy to dev"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::986761640373:role/github-lambda-create-role
      - name: Deploy to Lambda
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: dev-lambda-ts
          code-artifacts-dir: ./dist
          handler: handler.handler
          runtime: nodejs22.x
          role: arn:aws:iam::986761640373:role/github-lambda-create-role
